config/routes.rb
Rails.application.routes.draw do
  get 'boards_controller/select_cell'

  root 'static_pages#home'

  resources :games, only: [:index, :new, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/boards_controller_controller.rb
class BoardsControllerController < ApplicationController
  def select_cell
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
    puts "Hello World!"
  end

  def new
    render 'index'
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end
end

app/helpers/board_helper.rb
module BoardHelper
end

app/helpers/boards_controller_helper.rb
module BoardsControllerHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/boards_controller/select_cell.html.erb
<h1>BoardsController#select_cell</h1>
<p>Find me in app/views/boards_controller/select_cell.html.erb</p>

app/views/games/index.html.erb
<div id='board'>
  <% 9.times do |i| %>
    <div class='tile<%= i %> tile'> 
      <% 9.times do |j| %>
	<div id='tile<%= i %>square<%= j %>' class='cell square<%= j %>' data-tile='<%= j %>' data-square='<%= j %>'></div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/layouts/_head.html.erb
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

app/views/layouts/_header.html.erb
<h1 class="center">Ultimate Tic Tac Toe</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <%= render 'layouts/head' %>
  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<div class = "center">
  <h2>A stategic boardgame for 2 players.</h2>
  <p>Win three games of Tic Tac Toe in a row.</br>
  You may only play in the big field that</br>
  corresponds to the last small field your</br>
  opponent played. When your are sent to a</br>
  field that is already decided, you can</br>
  choose freely.</p>

  <p>You can find a better write up of the rules <%= link_to "here", 'https://mathwithbaddrawings.com/2013/06/16/ultimate-tic-tac-toe/' %>.</p>

  <p>It should work on most devices.</br>
  Javascript and cookies should be enabled.</p>

  <p><%=link_to "Start a new game", games_path %></p>
</div>